secrets: &secrets
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
  admin_secret_key: <%= ENV["ADMIN_SECRET_KEY"] %>
  admin_email: <%= ENV["ADMIN_EMAIL"] %>

development:
  <<: *secrets

test:
  <<: *secrets

production:
  <<: *secrets
